feat: Create modal Hash and modal Codigo
juserrrrr/4vote-web pull request #14
Opened 2024-06-15 14:03 UTC by IMCNeto

Criei o componente referente a o modal do Código e do Hash
Tem dois arquivos, o principal que é correspondente ao componente e o arquivo referente a variação do modal(Hash ou código)

Teste modal Hash
![image](https://github.com/juserrrrr/4vote-web/assets/143047526/75aec8ce-20a0-4358-a4ad-e04d5cb84cd4)

Teste modal código
![image](https://github.com/juserrrrr/4vote-web/assets/143047526/4cc6b2df-fd2f-43ad-8d29-4036b09628b1)

2024-06-15 20:01 UTC, mendes658 approved these changes

2024-06-16 21:57 UTC, juserrrrr requested changes

2024-06-16 21:57 UTC, juserrrrr commented on package.json
Tenta fazer sem usar biblioteca pra modal, pra aprender com funciona a estilização do css, disso, não é mt difícil e fica como aprendizagem, fora que só vai usar essa biblioteca uma única vez.

2024-06-16 21:57 UTC, juserrrrr commented on src/app/components/modal/modal.tsx
> +  isOpennow: boolean;
isOpenNow

2024-06-16 21:57 UTC, juserrrrr commented on src/app/components/modal/modal.tsx
O input tem q ser usado no nosso estilo, já tem componente feito pra isso

2024-06-16 21:57 UTC, juserrrrr commented on src/app/components/modal/modal.tsx
Os botões também já tem criados como componente.

2024-06-17 22:35 UTC, IMCNeto commented on package.json
Feito

2024-06-17 22:36 UTC, IMCNeto commented on src/app/components/modal/modal.tsx
Feito

2024-06-17 22:42 UTC, IMCNeto commented
Fiz as alterações

2024-06-17 22:43 UTC, juserrrrr approved these changes

2024-06-17 22:43 UTC, merged