Lm/Taskt019
juserrrrr/4vote-web pull request #16
Opened 2024-06-16 18:37 UTC by LuisMarioRC

Criando Modal do Filtro & Ordenar por
![Captura de tela 2024-06-16 144615](https://github.com/juserrrrr/4vote-web/assets/142133059/bce027f7-b30a-445d-b662-7b66d5dd8684)
![Captura de tela 2024-06-16 152433](https://github.com/juserrrrr/4vote-web/assets/142133059/ea1c5381-1ad3-4261-a6e8-e4e5d55a3997)

2024-06-16 23:54 UTC, Fernanda-Marinho approved these changes

2024-06-17 15:54 UTC, juserrrrr requested changes

2024-06-17 15:54 UTC, juserrrrr commented on src/components/modalsFilters/checkbox.tsx
Como que quem tá no componente pai vai ter acesso ao checkbox? tem que fazer aquela parada de o checkbox receber o estado do componente pai

2024-06-17 19:57 UTC, juserrrrr approved these changes

2024-06-17 19:58 UTC, merged