N/task041
juserrrrr/4vote-web pull request #18
Opened 2024-06-17 01:00 UTC by naylane

2024-06-17 23:03 UTC, naylane commented
Eu tinha tentado colocar um boolean que alterasse o texto do componente dependendo da entrada. Agora tirei porque não sei como essa parte funcionaria com o resto da aplicação

2024-06-17 23:08 UTC, juserrrrr requested changes

2024-06-17 23:08 UTC, juserrrrr commented on src/components/validation/validationResult.tsx
> +  };
Fazer operador ternário somente onde é alterado os valores.
Exemplo da div
<div className={fontStyle}>{answer ?'VOTO VÁLIDO': 'VOTO INVÁLIDO'}</div>

Aplicar isso na imagem também. lembra de aplica isso diretamente no return da função principal do componente e apagar a const render.

2024-06-18 00:56 UTC, juserrrrr approved these changes

2024-06-20 15:02 UTC, mendes658 approved these changes

2024-06-20 15:02 UTC, merged